server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: Student-Management
  # MySQL数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_service?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: test_password
    hikari:
      pool-name: HikariCP-Test
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      leak-detection-threshold: 5000

  # MongoDB配置
  data:
    mongodb:
      uri: mongodb://localhost:27017/student_management_test

  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 1
    timeout: 10000
    lettuce:
      pool:
        max-active: 16
        max-wait: -1
        max-idle: 16
        min-idle: 4
  
  # 缓存配置
  cache:
    redis:
      time-to-live: 3600000 # 1小时，测试环境缓存时间

  # Kafka配置
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: student-management-test-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 25MB
  
  # MVC配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  
  # JWT配置
  jwt:
    secret: test-secret-key-for-jwt-token-authentication
    expiration: 43200000 # 12小时
    token-prefix: Bearer
    header: Authorization
  
  # 跨域配置
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.studentManagement.entity,com.example.common.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      table-underline: true
    banner: false

# Actuator监控配置
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env"
  endpoint:
    health:
      show-details: always
    info:
      enabled: true

# Swagger配置
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
  swagger:
    ui:
      enabled: true

# 测试环境日志级别
logging:
  level:
    com.example.student-management: info
    org.springframework: warn
    org.hibernate.SQL: info
