spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://test-mysql:3306/student_db_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: test_user
    password: test_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: StudentServiceHikariCP-TEST
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Redis配置
  data:
    redis:
      host: test-redis
      port: 6379
      password: test_redis_password
      database: 0
      timeout: 3000ms
      jedis:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: -1ms

  # Kafka配置
  kafka:
    bootstrap-servers: test-kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
      acks: all
    consumer:
      group-id: student-service-test-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  # Nacos配置 (暂时注释，后续启用)
  # cloud:
  #   nacos:
  #     discovery:
  #       server-addr: test-nacos:8848
  #       namespace: test
  #       group: DEFAULT_GROUP
  #     config:
  #       server-addr: test-nacos:8848
  #       file-extension: yml
  #       namespace: test
  #       group: DEFAULT_GROUP

# 测试环境日志配置
logging:
  level:
    com.example.student: INFO
    com.example.common: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: INFO 