spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://prod-mysql:3306/teacher_db_prod?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:prod_user}
    password: ${DB_PASSWORD:prod_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: TeacherServiceHikariCP-PROD
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:prod-redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:prod_redis_password}
      database: 1
      timeout: 3000ms
      jedis:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 5
          max-wait: -1ms

  # Kafka配置
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:prod-kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 5
      batch-size: 32768
      linger-ms: 5
      buffer-memory: 67108864
      acks: all
    consumer:
      group-id: teacher-service-prod-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  # Nacos配置 (暂时注释，后续启用)
  # cloud:
  #   nacos:
  #     discovery:
  #       server-addr: ${NACOS_SERVER:prod-nacos:8848}
  #       namespace: ${NACOS_NAMESPACE:prod}
  #       group: ${NACOS_GROUP:DEFAULT_GROUP}
  #     config:
  #       server-addr: ${NACOS_SERVER:prod-nacos:8848}
  #       file-extension: yml
  #       namespace: ${NACOS_NAMESPACE:prod}
  #       group: ${NACOS_GROUP:DEFAULT_GROUP}

# 生产环境日志配置
logging:
  level:
    com.example.teacher: INFO
    com.example.common: INFO
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.hibernate.SQL: ERROR
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
  file:
    name: /var/log/teacher-service/application.log
    max-size: 100MB
    max-history: 30 